name: gpxtrackposter

services:
    create:
        build: ./
        image: gpxtrackposter:latest
        restart: "no"
        env_file:
            - .env
        command: "/usr/local/bin/create_poster \
            --type ${TYPE:-'grid'} \
            --title ${TITLE:-'Running'} \
            --year ${YEAR:-'2024'} \
            --athlete ${ATHLETE:-'John Doe'} \
            --units ${UNITS:-'metric'} \
            --gpx-dir /usr/src/app/gpx \
            ${EXTRA_OPTIONS:-'--verbose'} \
            --output /usr/src/app/output/output.svg"
        volumes:
            - ./output:/usr/src/app/output
            - ./gpx:/usr/src/app/gpx
