name: CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies - ${{runner.os}}
      if: runner.os == 'Windows'
      run: |
        sed -i '/disable=/a \    no-member,' .pylintrc
    - name: Set up Python v${{matrix.python-version}} - ${{runner.os}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
        cache: pip
    - name: Display Python version
      run: python --version
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Check formatting (black)
      run: black --line-length 120 --check --diff gpxtrackposter tests scripts
    - name: Lint (pylint)
      run: pylint gpxtrackposter tests scripts
    - name: Check types (mypy)
      run: mypy gpxtrackposter tests scripts
    - name: Check spelling (codespell)
      run: codespell README.md gpxtrackposter/*.py tests/*.py scripts/*.py
    - name: Run tests (pytest) with coverage
      run: |
        sudo locale-gen --lang de_DE.UTF-8
        sudo locale-gen --lang en_US.UTF-8
        sudo locale-gen --lang zh_CN.UTF-8
        python -m pytest --cov=gpxtrackposter --cov-branch --cov-report=term --cov-report=html -m "not full_run" tests
